Revert "cask: Only enable on macOS"
This reverts commit fe7caf7cd8a413fb1118f6149ac2cf3acafd63de.

Brew gives an error message for `brew cask install`.
Error: Installing casks is supported only on macOS