test_gpg: tweak rmtree usage
Swats away this annoying warning when the test is skipped due to GPG being
unavailable:

```
  1) Skipped:
GpgTest#test_create_test_key:
GPG Unavailable

Error:
GpgTest#test_create_test_key:
NoMethodError: undefined method `rmtree' for nil:NilClass
    /usr/local/Library/Homebrew/test/test_gpg.rb:11:in `teardown'
```

Closes #675.

Signed-off-by: Dominyk Tiller <dominyktiller@gmail.com>