Python.user_site_packages: Check python suceeds [Linux]
Python 2.6 does not provide site.getusersitepackages()
Fix AttributeError: 'module' object has no attribute 'getusersitepackages'

Fixes https://github.com/Linuxbrew/brew/issues/557